package cfgx

import (
	"errors"
	"fmt"
	"reflect"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

const (
	pathBytes         = "<bytes>"
	pathStruct        = "<struct>"
	fieldDot          = "."
	indexLBracket     = "["
	indexRBracket     = "]"
	tagYAML           = "yaml"
	tagJSON           = "json"
	tagTOML           = "toml"
	tagIgnore         = "-"
	tagInline         = "inline"
	autogeneratedFile = "<autogenerated>"
)

var validatorIface = reflect.TypeOf((*Validator)(nil)).Elem()

// Validate walks dst and invokes every nested [Validator] (post-order:
// children, then parent) with the given fix flag. Remaining errors are
// joined under [ErrValidationFailed] with a field path prefix.
//
// The walk descends exported struct fields, then slice/array elements and
// map values whose element type can hold a [Validator] (struct, pointer,
// interface, or a nested collection of those). Leaf slices such as
// []string are not descended. Map values are copied so pointer-receiver
// autofix can persist. Exported anonymous embeds that implement [Validator]
// are invoked once on the field, not again via a promoted method on the
// parent. Nil pointer embeds are skipped and do not panic.
//
// Call this at the end of the cfgx → envx → clix pipeline so nested
// validators see the final values. [Load]/[Parse] still validate the
// file-only state. dst must be a non-nil pointer.
//
// Pass [WithFormat] so path prefixes use the same struct tags as the file
// codec. Without it, [FormatAuto] prefers yaml → json → toml and falls
// through a "-" tag to the next codec.
func Validate(dst any, fix bool, opts ...Option) error {
	if err := requirePointer("dst", dst); err != nil {
		return err
	}
	cfg := newConfig(opts)
	format := cfg.format
	if format != FormatAuto {
		if err := requireExplicitFormat(format, pathStruct); err != nil {
			return err
		}
	}
	return runValidator(pathStruct, dst, fix, format)
}

// runValidator is the single entry from [Load], [Parse], [loadMissing], and
// [Validate]. dst is already a non-nil pointer ([requirePointer]).
func runValidator(file string, dst any, fix bool, format Format) error {
	return walkValidate(reflect.ValueOf(dst), file, "", fix, format, map[uintptr]bool{})
}

func walkValidate(v reflect.Value, file, fieldPath string, fix bool, format Format, visited map[uintptr]bool) error {
	v, ok := derefValidate(v, visited)
	if !ok {
		return nil
	}

	var childErrs []error
	switch v.Kind() {
	case reflect.Struct:
		childErrs = walkStructFields(v, file, fieldPath, fix, format, visited)
	case reflect.Slice, reflect.Array:
		if descendable(v.Type()) {
			childErrs = walkIndexed(v, file, fieldPath, fix, format, visited)
		}
	case reflect.Map:
		if descendable(v.Type()) {
			childErrs = walkMap(v, file, fieldPath, fix, format, visited)
		}
	}

	selfErr := callValidator(v, file, fieldPath, fix, format)
	return errors.Join(append(childErrs, selfErr)...)
}

func walkStructFields(v reflect.Value, file, fieldPath string, fix bool, format Format, visited map[uintptr]bool) []error {
	var childErrs []error
	t := v.Type()
	for i := 0; i < t.NumField(); i++ {
		sf := t.Field(i)
		if !sf.IsExported() {
			continue
		}
		fv := v.Field(i)
		name, skip, inline := fieldSegment(sf, format)
		if skip {
			continue
		}
		childPath := fieldPath
		if !inline && name != "" {
			if childPath == "" {
				childPath = name
			} else {
				childPath = childPath + fieldDot + name
			}
		}
		if err := walkValidate(fv, file, childPath, fix, format, visited); err != nil {
			childErrs = append(childErrs, err)
		}
	}
	return childErrs
}

func walkIndexed(v reflect.Value, file, fieldPath string, fix bool, format Format, visited map[uintptr]bool) []error {
	var childErrs []error
	n := v.Len()
	for i := 0; i < n; i++ {
		p := indexPath(fieldPath, strconv.Itoa(i))
		if err := walkValidate(v.Index(i), file, p, fix, format, visited); err != nil {
			childErrs = append(childErrs, err)
		}
	}
	return childErrs
}

func walkMap(v reflect.Value, file, fieldPath string, fix bool, format Format, visited map[uintptr]bool) []error {
	keys := v.MapKeys()
	sort.Slice(keys, func(i, j int) bool {
		return mapKeyString(keys[i]) < mapKeyString(keys[j])
	})
	var childErrs []error
	for _, key := range keys {
		mv := v.MapIndex(key)
		p := indexPath(fieldPath, mapKeyString(key))
		err := walkMapValue(v, key, mv, file, p, fix, format, visited)
		if err != nil {
			childErrs = append(childErrs, err)
		}
	}
	return childErrs
}

func walkMapValue(m, key, mv reflect.Value, file, fieldPath string, fix bool, format Format, visited map[uintptr]bool) error {
	if !mv.IsValid() {
		return nil
	}
	switch mv.Kind() {
	case reflect.Pointer, reflect.Interface:
		return walkValidate(mv, file, fieldPath, fix, format, visited)
	}
	if !mv.CanInterface() {
		return nil
	}
	cpy := reflect.New(mv.Type())
	cpy.Elem().Set(mv)
	err := walkValidate(cpy, file, fieldPath, fix, format, visited)
	if fix {
		m.SetMapIndex(key, cpy.Elem())
	}
	return err
}

func descendable(t reflect.Type) bool {
	for {
		switch t.Kind() {
		case reflect.Pointer, reflect.Slice, reflect.Array, reflect.Map:
			t = t.Elem()
		case reflect.Struct, reflect.Interface:
			return true
		default:
			return false
		}
	}
}

func indexPath(base, index string) string {
	seg := indexLBracket + index + indexRBracket
	if base == "" {
		return seg
	}
	return base + seg
}

func mapKeyString(k reflect.Value) string {
	if k.Kind() == reflect.String {
		return k.String()
	}
	if k.CanInterface() {
		return fmt.Sprint(k.Interface())
	}
	return k.Kind().String()
}

func derefValidate(v reflect.Value, visited map[uintptr]bool) (reflect.Value, bool) {
	for {
		if !v.IsValid() {
			return v, false
		}
		switch v.Kind() {
		case reflect.Interface, reflect.Pointer:
			if v.IsNil() {
				return v, false
			}
			if v.Kind() == reflect.Pointer {
				ptr := v.Pointer()
				if visited[ptr] {
					return v, false
				}
				visited[ptr] = true
			}
			v = v.Elem()
		default:
			return v, true
		}
	}
}

func callValidator(v reflect.Value, file, fieldPath string, fix bool, format Format) error {
	if !v.IsValid() {
		return nil
	}
	if v.Kind() == reflect.Pointer && v.IsNil() {
		return nil
	}
	if skipPromotedValidator(v, format) {
		return nil
	}
	var iv any
	switch {
	case v.Kind() != reflect.Pointer && v.CanAddr():
		iv = v.Addr().Interface()
	case v.CanInterface():
		iv = v.Interface()
	default:
		return nil
	}
	val, ok := iv.(Validator)
	if !ok {
		return nil
	}
	return errValidationFailed(file, fieldPath, val.Validate(fix))
}

func skipPromotedValidator(v reflect.Value, format Format) bool {
	methodType := v.Type()
	if v.Kind() == reflect.Struct && v.CanAddr() {
		methodType = reflect.PointerTo(v.Type())
	}
	m, ok := methodType.MethodByName("Validate")
	if !ok {
		return false
	}
	f := runtime.FuncForPC(m.Func.Pointer())
	if f == nil {
		return false
	}
	file, _ := f.FileLine(m.Func.Pointer())
	structType := methodType
	if structType.Kind() == reflect.Pointer {
		structType = structType.Elem()
	}
	if structType.Kind() != reflect.Struct {
		return false
	}
	walkedEmbedValidator := false
	for i := 0; i < structType.NumField(); i++ {
		sf := structType.Field(i)
		if !sf.Anonymous || !sf.IsExported() || !typeImplementsValidator(sf.Type) {
			continue
		}
		if _, skip, _ := fieldSegment(sf, format); skip {
			continue
		}
		walkedEmbedValidator = true
		break
	}
	if !walkedEmbedValidator {
		return false
	}
	return file == autogeneratedFile
}

func typeImplementsValidator(t reflect.Type) bool {
	if t.Implements(validatorIface) {
		return true
	}
	return t.Kind() != reflect.Pointer && reflect.PointerTo(t).Implements(validatorIface)
}

func fieldSegment(sf reflect.StructField, format Format) (name string, skip, inline bool) {
	if key := formatTag(format); key != "" {
		return parseStructTag(sf.Tag.Get(key), sf.Name)
	}
	sawIgnore := false
	for _, key := range []string{tagYAML, tagJSON, tagTOML} {
		tag := sf.Tag.Get(key)
		if tag == "" {
			continue
		}
		name, skip, inline = parseStructTag(tag, sf.Name)
		if skip {
			sawIgnore = true
			continue
		}
		return name, false, inline
	}
	if sawIgnore {
		return "", true, false
	}
	return sf.Name, false, false
}

func formatTag(format Format) string {
	switch format {
	case FormatJSON:
		return tagJSON
	case FormatTOML:
		return tagTOML
	case FormatYAML:
		return tagYAML
	default:
		return ""
	}
}

func parseStructTag(tag, goName string) (name string, skip, inline bool) {
	if tag == tagIgnore {
		return "", true, false
	}
	parts := strings.Split(tag, ",")
	name = parts[0]
	for _, p := range parts[1:] {
		if p == tagInline {
			inline = true
		}
	}
	if name == tagIgnore {
		return "", true, false
	}
	if name == "" && !inline {
		name = goName
	}
	return name, false, inline
}
